### ISSUE TITLE
missing LICENSE.txt

### ISSUE THREAD

**Issue by uwabami** [gfd-dennou-club/ruby-mpi#13]
今更ですが、気がついたので。

**Comment by seiya** [comment]
すいません。
トップディレクトリに LICENSE.txt はあるのですが、何か置き方や書き方が間違っているという意味でしょうか？
https://github.com/gfd-dennou-club/ruby-mpi/blob/master/LICENSE.txt

**Comment by uwabami** [comment]
節穴でした。すみません…。

**Comment by uwabami** [comment]
なんでそう思ったんでしょうか。大変失礼いたしました…。
