### ISSUE TITLE
mpi_alltoallv and mpi_alltoallw

### ISSUE THREAD

**Issue by bkmgit** [gfd-dennou-club/ruby-mpi#8]
Consider adding [mpi_alltoallv](https://www.mpich.org/static/docs/latest/www3/MPI_Alltoallv.html) and/or [mpi_altoallw](https://www.mpich.org/static/docs/latest/www3/MPI_Alltoallw.html)

**Comment by seiya** [comment]
I am going to add some functions including mpi_alltoallv.

To implement mpi_alltoallw, handling multiple types is necessary.
In the current implementation, the data type is determined by the buffer type (type of NArray).
A NArray object has only one data type.
Therefore, it is difficult to handle multiple types with the current way.
What kinds of API do you think are possible for mpi_alltoallw?

**Comment by bkmgit** [comment]
Happy to implement mpi_alltoallv if that is ok, though will likely need some review 

Probably before adding many other MPI functions, may want to also look at:
- Using [Numo NArray](https://github.com/ruby-numo/numo-narray)
- Ruby Bindings for [UPC](http://upc-lang.org/)
- Ruby Bindings for C specification of [XcalableMP](https://xcalablemp.org)
- Direct build on top of [Gasnet](https://gasnet.lbl.gov/)
- Direct build on top of [GPI 2](https://github.com/cc-hpc-itwm/GPI-2)
- Direct build on top of [UCS](https://www.openucx.org/)
- Good ways to architect a distributed memory version of [Rumale](https://github.com/yoshoku/rumale)

**Comment by seiya** [comment]
I added some functions and pushed the blanch (feature/mpi_functions).
Could you confirm that the alltoallv is working as expected?

**Comment by bkmgit** [comment]
Thanks will check it out.
